# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
sqlite: &sqlite
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/<%= Rails.env %>.sqlite3

#Default configuration to local machine fedora, database IRBDB 
defaults: &defaults
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /opt/lampp/var/mysql/mysql.sock

#Default configuration to CLOUD9, database c9
#defaults: &defaults
#  adapter: mysql2
#  encoding: utf8
#  username: <%=ENV['C9_USER']%>
#  host: <%=ENV['IP']%>

development:
  <<: *defaults
  database: IRBDB_v3

test: &test
  <<: *defaults

production:  
  <<: *defaults
  database: IRBDB_V3_Prod